input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/altars python parsers/altars.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/bought python parsers/bought.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/conclusion python parsers/conclusion.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/fell python parsers/fell.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/found python parsers/found.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/identified python parsers/identified.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/killed python parsers/killed.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/learned python parsers/learned.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/mutation python parsers/mutation.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/noticed python parsers/noticed.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/orb python parsers/orb.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/rune python parsers/rune.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/shaft python parsers/shaft.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/skill_progression python parsers/skill_progression.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/unlearned python parsers/unlearned.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/upgrades python parsers/upgrades.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/win python parsers/win.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/worship python parsers/worship.py;
input_path=/Users/ben/warehouse_crawl-data/morgues-split/0.23/notes/ output_path=/Users/ben/warehouse_crawl-data/morgues-parsed/0.23/xp_progression python parsers/xp_progression.py;

path=data/0.23/action_totals/ python parsers/action_totals.py;
path=data/0.23/final_abilities/ python parsers/final_abilities_parser.py;
path=data/0.23/final_altars/ python parsers/final_altars_parser.py;
path=data/0.23/final_skills/ python parsers/final_skills_parser.py;
path=data/0.23/final_stats/ python parsers/final_stats_parser.py;
path=data/0.23/final_vanquished/ python parsers/final_vanquished_parser.py;
path=data/0.23/game_seed/ python parsers/game_seed_parser.py;
path=data/0.23/game_version/ python parsers/game_version_parser.py;

mkdir data/0.23/summaries;

cat data/0.23/notes/altars/*.csv > data/0.23/summaries/altars.csv;
cat data/0.23/notes/bought/*.csv > data/0.23/summaries/bought.csv;
cat data/0.23/notes/conclusion/*.csv > data/0.23/summaries/conclusion.csv;
cat data/0.23/notes/fell/*.csv > data/0.23/summaries/fell.csv;
cat data/0.23/notes/found/*.csv > data/0.23/summaries/found.csv;
cat data/0.23/notes/identified/*.csv > data/0.23/summaries/identified.csv;
cat data/0.23/notes/killed/*.csv > data/0.23/summaries/killed.csv;
cat data/0.23/notes/learned/*.csv > data/0.23/summaries/learned.csv;
cat data/0.23/notes/mutation/*.csv > data/0.23/summaries/mutation.csv;
cat data/0.23/notes/noticed/*.csv > data/0.23/summaries/noticed.csv;
cat data/0.23/notes/rune/*.csv > data/0.23/summaries/rune.csv;
cat data/0.23/notes/orb/*.csv > data/0.23/summaries/orb.csv;
cat data/0.23/notes/shaft/*.csv > data/0.23/summaries/shaft.csv;
cat data/0.23/notes/skill_progression/*.csv > data/0.23/summaries/skill_progression.csv;
cat data/0.23/notes/unlearned/*.csv > data/0.23/summaries/unlearned.csv;
cat data/0.23/notes/upgrades/*.csv > data/0.23/summaries/upgrades.csv;
cat data/0.23/notes/win/*.csv > data/0.23/summaries/win.csv;
cat data/0.23/notes/worship/*.csv > data/0.23/summaries/worship.csv;
cat data/0.23/notes/xp_progression/*.csv > data/0.23/summaries/xp_progression.csv;
cat data/0.23/action_totals/*.csv > data/0.23/summaries/action_totals.csv;
cat data/0.23/final_abilities/*.csv > data/0.23/summaries/final_abilities.csv;
cat data/0.23/final_altars/*.csv > data/0.23/summaries/final_altars.csv;
cat data/0.23/final_skills/*.csv > data/0.23/summaries/final_skills.csv;
cat data/0.23/final_stats/*.csv > data/0.23/summaries/final_stats.csv;
cat data/0.23/final_vanquished/*.csv > data/0.23/summaries/final_vanquished.csv;
cat data/0.23/game_seed/*.csv > data/0.23/summaries/game_seed.csv;
cat data/0.23/game_version/*.csv > data/0.23/summaries/game_version.csv;
