name: Dungeon Crawler Warehouse
data: /Users/seb/Development/dcss-data/data
jobs:
  download:
    - name: morgues-download
      transform: morgues-download
      base_url: http://crawl.develz.org/morgues/0.23/
      throttle: 1000
      output: data:///data/morgues

    - transform: morgue-splitter
      morgues: ${morgues-download.output}
      output: data:///morgue-splits
