name: Dungeon Crawler Warehouse
jobs:
  - processor: morgues-download
    base_url: http://crawl.develz.org/morgues/0.23/
    throttle: 1000
    output: /tmp/data/morgues
  
  - processor: morgue-splitter
    morgues: /tmp/data/morgues
    output: /tmp/data/splits
