name: Dungeon Crawler Warehouse
data: /tmp/data/
jobs:
  download:
    - transform: morgues-download-2
      base_url: http://crawl.berotato.org/crawl/morgue/
      throttle: 500
      output: /tmp/data/morgues

  preprocess:
    - transform: index-versions
      morgues: /tmp/data/morgues
      output: /tmp/data/morgues-by-version/
